# Generated by Django 4.2.6 on 2024-03-02 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_rename_owner_communitychat_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="communitychat",
            old_name="User",
            new_name="user",
        ),
    ]
